In [5]:
import numpy as np

In [4]:
a = np.array(np.random.randint(50,99,(3,4)))
print(a)

[[98 75 92 75]
 [82 68 50 67]
 [86 66 69 84]]


Create an Array like
```
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
 
```

In [11]:
x = np.zeros((7,7))
print(x)

y = np.ones((5,5))
y[2,2] = 5
print(y)

x[1:-1, 1:-1] = y

print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [14]:
print( x * np.identity(7))


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[ 9 18 12 11]
 [ 8 20  6 19]
 [10  5 10  7]] [[98 75 92 75]
 [82 68 50 67]
 [86 66 69 84]]


In [19]:
b = np.random.randint(5, 23, size= a.shape)

print(b)

print(a)

print(a * b)

[[ 9 10 10 20]
 [12 13 19 13]
 [21 17  8 20]]
[[98 75 92 75]
 [82 68 50 67]
 [86 66 69 84]]
[[ 882  750  920 1500]
 [ 984  884  950  871]
 [1806 1122  552 1680]]


In [22]:
ones = np.ones((2,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
